name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

env:
  GOLANGCI_LINT_VERSION: latest

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Go (from go.mod)
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true

      - name: go mod tidy
        run: |
          go mod tidy
          git diff --exit-code

  test-and-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    needs: [validate]
    strategy:
      fail-fast: false
      matrix:
        go: ['1.24.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
          cache: true

      - name: Cache Go build
        uses: actions/cache@v4
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-gobuild-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gobuild-${{ matrix.go }}-

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./... -coverprofile=coverage.txt

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: "${{ env.GOLANGCI_LINT_VERSION }}"
          args: >
            --timeout=10m
            ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
