name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  GOLANGCI_LINT_VERSION: latest

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go (from go.mod)
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: go mod tidy check
        run: |
          go mod tidy
          git diff --exit-code

      - name: go vet
        run: go vet ./...

  test-and-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    needs: [validate]
    strategy:
      fail-fast: false
      matrix:
        go: ['1.24.x']   # add more if you want to test multiple versions

    steps:
      - uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -race -covermode=atomic -coverprofile=coverage.txt ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: "${{ env.GOLANGCI_LINT_VERSION }}"
          args: >
            --timeout=10m
            ./...

      - name: Upload coverage to Codecov
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false
        uses: codecov/codecov-action@v5
        with:
          files: coverage.txt